# active spring boot profile
spring:
  application:
    name: emaillist
  profiles:
    active: development








---
# common configuration
spring:
  mvc:
    # Path pattern used for static resources
    static-path-pattern: /assets/** # asset으로 들어오는 건 모두 static에서 찾는다

    # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # Locations of static resources
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    mode: HTML5
    suffix: .html
    cache: false

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml









---
# development configuration
spring:
  config:
    activate:
      on-profile: development

  # devtools - live reload
  devtools:
    livereload:
      enabled: true
      
  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

# logging
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: WARN





---
# production configuration
spring:
  config:
    activate:
      on-profile: production

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# server
server:
  port: 8880
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      
logging:
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
  file:
    name: logs/${spring.application.name}.log
    max-history: 30
  level:
    root: INFO
    com:
       example:
          demo:
             exception: ERROR
