# active spring boot profile
spring:
  profiles:
    active: development

---
# common configuration
spring:
  mvc:
    # Path pattern used for static resources
    static-path-pattern: /assets/** # asset으로 들어오는 건 모두 static에서 찾는다

    # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # Locations of static resources
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    mode: HTML5
    suffix: .html
    cache: false

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml

# logging
logging:
  level:
    root: WARN

---
# development configuration
spring:
  config:
    activate:
      on-profile: development

  # devtools - live reload
  devtools:
    livereload:
      enabled: true

# server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

---
# production configuration
spring:
  config:
    activate:
      on-profile: production

# server
server:
  port: 8880
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
