# active profile
spring:
   profiles:
      active: development
      
---
#
# common configuration
#
spring:
   mvc:
      # path pattern used for static resources
      static-path-pattern: /assets/**

      # whether a "NoHandlerFoundException" should be thrown if no handler was found to process a request
      throw-exception-if-no-handler-found: true
   web:
      resources:
         # locations of static resources
         static-locations: classpath:/static/, file:D:/upload-images/
         
   # template engine: thymeleaf    
   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML
      suffix: .html
      cache: false
   
   # multipart uploads
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# logging
logging:
   level:
      root: INFO
         
---
#
# development profile configuration
#
spring:
   config:
      activate:
         on-profile: development

   # devtools enabled
   devtools:
      livereload:
         enabled: true

   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   

# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         

---
#
# production profile configuration
#
spring:
   config:
      activate:
         on-profile: production
              
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   
         
# server
server:
   port: 8882
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
