# active profile
spring:
  application:
    name: mysite
  profiles:
    active: development

---
#
# common configuration
#
spring:
  mvc:
    # path pattern used for static resources
    static-path-pattern: /assets/**

    # whether a "NoHandlerFoundException" should be thrown if no handler was found to process a request
    throw-exception-if-no-handler-found: true

  # template engine: thymeleaf
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    mode: HTML
    suffix: .html
    cache: false

  # multipart uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml

---
#
# development profile configuration
#
spring:
  config:
    activate:
      on-profile: development

  # devtools enabled
  devtools:
    livereload:
      enabled: true

  web:
    resources:
      # locations of static resources
      static-locations: classpath:/assets/, file:D:/upload-images/

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

# logging
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: WARN

---
#
# production profile configuration
#
spring:
  config:
    activate:
      on-profile: production

  web:
    resources:
      # locations of static resources
      static-locations: classpath:/assets/, file:/upload-images/

  # datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.0.67:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb

# server
server:
  port: 8881
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

logging:
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
  file:
    name: logs/${spring.application.name}.log
    max-history: 30
  level:
    root: INFO
    com:
      example:
        demo:
          exception: ERROR
